import random

# def shiftary(a):
#     a = list(a)
#     loops = random.choice([1,2,3,4]) #^ '4' is arbitray, and assume there are at least classes of type (biology, insects, etc)
#     for j in range(loops):
#         items = a[:5] #^ 5 is half of 10, which is the the number of elements in easy class aray (of biology, insects, etc)
#         for item in items:
#             a.remove(item)
#             a.append(item)
#     return a


pre = [
    "realistic photographic portrait",
    "realistic photographic portrait "
    # f"black and white pen and ink drawing",
    # f"polaroid photograph",
    # f"black and white photograph",
    # f"brownie camera photograph"
]

background = [
    "blackness",
    "dark black",
]

places=[
    "forest",
    "jungle",
    "swamp",
    # "desert",
    # "mountain",
    # "lake",
    "valley",
    # "city",
    # "town",
    # "road",
    "outerspace",
    "outer space",
    "river",
    # "war",
    # "slum",
    # "car"
]

adj = ["amazed","aggravated","anxious","attractive","awful","awestruck","bold","chilly","bashful","brave","dejected","cautious","bubbly","dirty","composed","cheerful","dreadful","easygoing","comfortable","heavy","horrified","delightful","irritated","intelligent","excited","pessimistic","numb","festive","tearful","puzzled","free","tense","quizzical","jolly","terrible","ravenous","optimistic","tired","reluctant","proud","ugly","settled","wonderful","weak","shy"]
# adj = ["colorful","pretty"]
verbs = ["arising","beating","betting","biting","bleeding","blowing","building","catching","creeping","cuting","drawing","dreaming","drinking","driving","eating","falling","feeding","fighting","fleeing","flying","freezing","hanging","hiding","hitting","holding","kneeling","leading","meeting","reading","riding","ringing","rising","running","sewing","shaking","shining","shooting","singing","sinking","siting","sleeping","sliding","speaking","spliting","standing","stinging","striking","sweeping","swimming","teaching","tearing","throwing","weaving","weeping","writing"]
# verbs = ["above","below"]

animals=[
    "ground hog",
    "prairie dog",
    "mare",
    "ram",
    "ape",
    "grizzly bear",
    "chipmunk",
    "chameleon",
    "donkey",
    "wildcat",
    "reindeer",
    "pony",
    "aardvark",
    "camel",
    "elk",
    "parakeet",
    "canary",
    "impala",
    "turtle",
    "mountain goat",
    "jaguar",
    "iguana",
    "hyena",
    "cheetah",
    "bighorn",
    "basilisk",
    "llama",
    "chimpanzee",
    "toad",
    "alligator",
    "bald eagle",
    "weasel",
    "rooster",
    "colt",
    "wolverine",
    "warthog",
    "panda",
    "musk-ox",
    "fox",
    "mustang",
    "chinchilla",
    "lion",
    "snowy owl",
    "rhinoceros",
    "silver fox",
    "otter",
    "antelope",
    "guinea pig",
    "puma",
    "polar bear",
    "wolf",
    "camel",
    "squirrel",
    "parrot",
    "dingo",
    "mule",
    "fish",
    "whale",
    "gazelle",
    "panther",
    "starfish",
    "dog",
    "pig",
    "walrus",
    "duckbill platypus",
    "deer",
    "giraffe",
    "mongoose",
    "newt",
    "raccoon",
    "anteater",
    "kitten",
    "kangaroo",
    "wombat",
    "moose",
    "lamb",
    "dung beetle",
    "peccary",
    "seal",
    "lovebird",
    "opossum",
    "gopher",
    "orangutan",
    "beaver",
    "buffalo",
    "armadillo",
    "hare",
    "blue crab",
    "meerkat",
    "mynah bird",
    "porcupine",
    "lynx",
    "bull",
    "horse",
    "leopard",
    "gila monster",
    "bison",
    "tiger",
    "baboon",
    "rat",
    "chicken",
    "snake",
    "civet",
    "ewe",
    "koala",
    "doe",
    "ibex",
    "stallion",
    "skunk",
    "fawn",
    "tapir",
    "muskrat",
    "ferret",
    "frog",
    "gnu",
    "jackal",
    "porpoise",
    "yak",
    "eagle owl",
    "bunny",
    "octopus",
    "elephant",
    "woodchuck",
    "zebra",
    "lizard",
    "marmoset",
    "musk deer",
    "mandrill",
    "badger",
    "crocodile",
    "mink",
    "ox",
    "cat",
    "shrew",
    "salamander",
    "bear",
    "hamster",
    "coyote",
    "alpaca",
    "puppy",
    "sloth",
    "rabbit",
    "goat",
    "hedgehog",
    "burro",
    "mole",
    "ocelot",
    "boar",
    "mouse",
    "sheep",
    "finch",
    "dormouse",
    "crow",
    "hog",
    "cougar",
    "monkey",
    "lemur",
    "cow",
    "hippopotamus",
    "marten",
    "capybara",
    "steer",
    "ermine",
    "gorilla",
    "bat"]
# birds=[
#     "Victoria Crowned Pigeon",
#     "Hadada Ibis",
#     "Roseate Spoonbill",
#     "Trumpeter Hornbill",
#     "White-headed Wattled Lapwing",
#     "Blue-bellied Roller",
#     "Green-winged Macaw",
#     "Golden-crested Mynah",
#     "Bateleur Eagle",
#     "Bald Eagle",
#     "Sun Conure",
#     "Common Grackle",
#     "Spectacled Owl",
#     "Harris's Hawk",
#     "Gouldian Finch",
#     "Cattle Egret",
#     "Cut-throat Finch",
#     "Collared Finch-Billed Bulbul",
#     "Melba Finch",
#     "Silver Gull",
#     "Rainbow Lorikeet",
#     "Guam Kingfisher",
#     "White-tailed Trogon",
#     "Black-faced Tanager",
#     "Augur Buzzard",
#     "American Crow",
#     "White-necked Raven",
#     "Andean Condor",
#     "Brown Pelican",
#     "European Starling",
#     "Military Macaw",
#     "Golden-breasted Starling",
#     "Ringed Teal",
#     "Boat-billed Heron",
#     "Blue-grey Tanager",
#     "Palm Cockatoo",
#     "Shaft-tailed Finch",
#     "Laughing Kookaburra",
#     "Hooded Vulture",
#     "Scarlet-headed Blackbird",
#     "Violaceous Euphonia",
#     "Snowy Owl",
#     "White-eared Catbird",
#     "Black Vulture",
#     "Malayan Great Argus",
#     "African Grey Parrot",
#     "Burrowing Owl",
#     "Keel-billed Toucan",
#     "Yellow-naped Amazon",
#     "Canary",
#     "Blue-crowned Motmot",
#     "White-cheeked Turaco",
#     "American Flamingo",
#     "Sunbittern",
#     "Hooded Merganser",
#     "Nicobar Pigeon",
#     "Black-faced Dacnis",
#     "Red-fronted Macaw",
#     "Two-toed Sloth",
#     "Inca Dove",
#     "Eastern Screech Owl",
#     "Bali Mynah",
#     "Scaly-sided Merganser",
#     "Crested Coua",
#     "Guam Rail",
#     "Smew",
#     "Blue-fronted Amazon Parrot",
#     "Indian Runner Duck",
#     "Snowy Egret",
#     "Taveta Golden Weaver",
#     "Bridled White-eye",
#     "Wattled Curassow",
#     "Green-naped Pheasant Pigeon",
#     "Scarlet Macaw",
#     "Sudan Golden Sparrow",
#     "Black-naped Fruit Dove",
#     "African Pygmy Falcon",
#     "Eurasian Eagle-Owl",
#     "Malayan Flying Fox",
#     "Inca Tern",
#     "Black Kite",
#     "Lanner Falcon",
#     "Green Singing Finch",
#     "Martial Eagle",
#     "White-throated Ground Dove",
#     "White-crested Laughing Thrush",
#     "Pied Imperial Pigeon",
#     "Purple-throated Fruit Crow",
#     "Scarlet Ibis",
#     "Scissor-tailed Flycatcher",
#     "Spangled Cotinga",
#     "Pekin Robin",
#     "Giant Cowbird",
#     "Dhyal Thrush",
#     "Greater Roadrunner",
#     "Ruddy Duck",
#     "Red-tailed Hawk",
#     "Black-headed Gonolek",
#     "Fairy Bluebird",
#     "Raggiana Bird-of-Paradise",
#     "Guira Cuckoo",
#     "Meyer's Parrot",
#     "Palm Tanager",
#     "Orange Bishop",
#     "Palawan Peacock-pheasant",
#     "Curl-crested Aracari",
#     "White-bellied Go-away-bird",
#     "Red Bishop Weaver",
#     "Green Woodhoopoe",
#     "Hamerkop",
#     "Green Aracari",
#     "Crested Wood Partridge",
#     "West Indian Whistling Duck",
#     "Southern Ground Hornbill",
#     "African Penguin",
#     "Rosybill Pochard",
#     "Troupial",
#     "Hyacinth Macaw",
#     "Brazilian Tanager",
#     "Paradise Whydah",
#     "Golden Conure",
#     "Red-legged Honeycreeper",
#     "Grey-winged Trumpeter",
#     "Rhinoceros Hornbill",
#     "Steller's Sea Eagle",
#     "Screaming Piha",
#     "Call Duck",
#     "Grosbeak Starling",
#     "Crested Oropendola",
#     "Southern Bald Ibis",
#     "Yellow-hooded Blackbird",
#     "Javan Pond Heron",
#     "American Kestrel"
# ]
birds=[
    "Pigeon",
    "Ibis bird",
    "Spoonbill bird",
    "Hornbill bird",
    "Macaw bird",
    "Mynah bird",
    "Eagle",
    "Grackle bird",
    "Owl",
    "Hawk",
    "Finch",
    "Egret",
    "Gull",
    "Kingfisher",
    "Buzzard",
    "Crow",
    "Raven",
    "Condor",
    "Pelican",
    "Starling bird",
    "Heron bird",
    "Tanager bird",
    "Cockatoo bird",
    "Kookaburra bird",
    "Vulture",
    "Blackbird",
    "Catbird",
    "Argus bird",
    "Parrot",
    "Toucan",
    "Canary",
    "Flamingo",
    "Dove",
    "Duck",
    "Egret",
    "Curassow bird",
    "Sparrow",
    "Falcon",
    "Tern bird",
    "Thrush bird",
    "Robin",
    "Cowbird",
    "Roadrunner",
    "Bluebird",
    "Bird-of-Paradise",
    "Cuckoo bird",
    "Peacock-pheasant",
    "Go-away-bird",
    "Partridge",
    "Hornbill bird",
    "Penguin",
    "Kestrel bird"
]
clothes=[
    "Scarf",
    "Cargos",
    "Poncho",
    "Blouse",
    "Dress",
    "Pajamas",
    "Tie",
    "Suit",
    "Gown",
    "Jeans",
    "Tights",
    "Fleece",
    "Polo Shirt",
    "Swimwear",
    "Thong",
    "Corset",
    "Boxers",
    "Coat",
    "Knickers",
    "Sunglasses",
    "Hoody",
    "Gloves",
    "Top",
    "Skirt",
    "Slippers",
    "Bikini",
    "Sandals",
    "Socks",
    "Shirt",
    "Briefs",
    "Belt",
    "Sarong",
    "Shawl",
    "Kilt",
    "Tankini",
    "Bow Tie",
    "Cufflinks",
    "Sweatshirt",
    "Cardigan",
    "T-Shirt",
    "Hat",
    "Robe",
    "Stockings",
    "Blazer",
    "Shoes",
    "Tracksuit",
    "Jogging Suit",
    "Nightgown",
    "Shorts",
    "Lingerie",
    "Jacket",
    "Dinner Jacket",
    "Waistcoat",
    "Swimming Shorts",
    "Cummerbund",
    "Boots",
    "Overalls",
    "Underwear",
    "Camisole",
    "Bra",
    "Cravat"
]
# fish=[
#     "triggerfish",
#     "scorpion fish",
#     "boxfish",
#     "bonito",
#     "butterflyfish",
#     "stonefish",
#     "clownfish",
#     "yellowfin tuna",
#     "angel fish",
#     "squirrelfish",
#     "skate",
#     "oyster toadfish",
#     "wahoo",
#     "speckled hind",
#     "scup",
#     "ocean sunfish",
#     "speckled trout",
#     "gray trout",
#     "tiger shark",
#     "batfish",
#     "mako shark",
#     "paddlefish",
#     "mandarin fish",
#     "amberjack",
#     "cusk",
#     "sea mullet",
#     "basselets",
#     "oarfish",
#     "sailfish",
#     "starfish",
#     "wolffish",
#     "albacore",
#     "mackerel",
#     "hickory shad",
#     "little tunny",
#     "flounder",
#     "needlefish",
#     "white grunt",
#     "surgeonfish",
#     "barracuda",
#     "vermillion snapper",
#     "sheepshead",
#     "scamp",
#     "striped bass",
#     "banded sea krait",
#     "king mackerel",
#     "goatfish",
#     "blueline tilefish",
#     "knobbed porgy",
#     "blacktip shark",
#     "lizardfish",
#     "pinfish",
#     "blobfish",
#     "pollock",
#     "bank sea bass",
#     "blackfin tuna",
#     "hogfish",
#     "salmon",
#     "whale shark",
#     "butterfish",
#     "croaker",
#     "cleaner fish",
#     "gnomefish",
#     "red drum",
#     "pigfish",
#     "drums",
#     "spanish mackerel",
#     "dolphin",
#     "gag grouper",
#     "alligator gar",
#     "swordfish",
#     "gray triggerfish",
#     "stingrays",
#     "bluefin tuna",
#     "bigeye tuna",
#     "spottail pinfish",
#     "spot",
#     "parrotfish",
#     "catfish",
#     "skipjack tuna",
#     "smelt",
#     "searobin",
#     "seahorse",
#     "plecostomus",
#     "cardinalfish",
#     "northern puffer",
#     "pompano",
#     "pufferfish",
#     "snapper",
#     "halibut",
#     "yellowedge grouper",
#     "bluefish",
#     "weakfish",
#     "puffers",
#     "silver snapper",
#     "unicornfish",
#     "damselfish",
#     "menhaden",
#     "hawkfish",
#     "flatfish",
#     "silver perch",
#     "tarpon",
#     "cobia",
#     "red snapper",
#     "black sea bass",
#     "cod",
#     "stingray",
#     "yellowtail snapper",
#     "black drum",
#     "flying fish",
#     "grouper",
#     "haddock",
#     "white marlin",
#     "rabbitfish",
#     "hammerhead",
#     "jumping mullet",
#     "red grouper",
#     "tautog",
#     "blue marlin",
#     "atlantic bonito",
#     "payara",
#     "spadefish"
# ]
fish=[
    "triggerfish",
    "boxfish",
    "butterflyfish",
    "stonefish",
    "clownfish",
    "trout fish",
    "batfish",
    "paddlefish",
    "basselets fish",
    "oarfish",
    "sailfish",
    "starfish",
    "wolffish",
    "albacore fish",
    "mackerel fish",
    "flounder fish",
    "needlefish",
    "barracuda fish",
    "goatfish",
    "lizardfish",
    "pinfish",
    "blobfish",
    "pollock fish",
    "tuna fish",
    "hogfish",
    "salmon fish",
    "butterfish",
    "croaker fish",
    "gnomefish",
    "pigfish",
    "mackerel fish",
    "dolphin fish",
    "grouper fish",
    "swordfish",
    "stingrays",
    "parrotfish",
    "catfish",
    "skipjack tuna",
    "smelt fish",
    "searobin fish",
    "seahorse",
    "cardinalfish",
    "pufferfish",
    "snapper fish",
    "halibut fish",
    "bluefish",
    "puffers fish",
    "unicornfish",
    "damselfish",
    "hawkfish",
    "flatfish",
    "tarpon fish",
    "cobia fish",
    "cod fish",
    "stingray",
    "grouper fish",
    "haddock fish",
    "marlin fish",
    "rabbitfish",
    "hammerhead fish",
    "spadefish"
]
# flowers=[
#     "Loosestrife
#     "Astilbe",
#     "Oleander",
#     "Snowdrops",
#     "Balloon Flower",
#     "Narcissus",
#     "Cosmos",
#     "Bellflower",
#     "Clematis",
#     "Larkspur",
#     "Geranium",
#     "Kerria",
#     "Rose of Sharon",
#     "Artemisia",
#     "Lobelia",
#     "Lavender",
#     "Anemone",
#     "Hosta",
#     "Trumpet Vine",
#     "Jupiter’s Beard",
#     "Crocus",
#     "Catmint",
#     "Silver Lace Vine",
#     "Marigold",
#     "Mock Orange",
#     "Lily-of-the-Valley",
#     "Hyacinth",
#     "Sedum",
#     "Butterfly Weed",
#     "Hardy Geranium",
#     "Blanketflower",
#     "Wisteria",
#     "Impatien",
#     "Hollyhock",
#     "New Guinea impatien",
#     "Lilac",
#     "Peony",
#     "Coneflower",
#     "Passion Flower",
#     "Lupine",
#     "Tulip",
#     "Shrub Roses",
#     "Chrysanthemum",
#     "Pansy",
#     "Bee Balm",
#     "Nicotiana",
#     "Vinca",
#     "Yarrow",
#     "Salvia",
#     "Dahlia",
#     "Lamium",
#     "Scilla",
#     "Gas Plant",
#     "Snap Dragon",
#     "Camellia",
#     "Morning Glory",
#     "Bougainvillea",
#     "Foxglove",
#     "Alyssum",
#     "Shasta Daisy",
#     "Sweet Pea",
#     "Bleeding Heart",
#     "Coral Bells",
#     "Aster",
#     "Columbine",
#     "Gladiolus",
#     "Poppy",
#     "Allium",
#     "Bachelor Button",
#     "Primrose",
#     "Petunias",
#     "Day Lily",
#     "Hybrid Tea Roses",
#     "Butterfly Bush",
#     "Broom",
#     "Iris",
#     "Globeflower",
#     "Moon Flower",
#     "Scabiosa",
#     "Coreopsis",
#     "Hydrangea",
#     "Nasturtium",
#     "Rhododendron",
#     "Grape Hyacinth",
#     "Cyclamen",
#     "Delphinium",
#     "Pinks",
#     "Gayfeather",
#     "Honeysuckle",
#     "Lantana",
#     "Snowball bush"
# ]
flowers=[
    "Red Rose flower",
    "White Orchid flower",
    "Yellow Chrysanthemum flower",
    "Purple Oleander flower",
    "Narcissus flower",
    "Geranium flower",
    "Lobelia flower",
    "Lavender flower",
    "Anemone flower",
    "Crocus flower",
    "Marigold flower",
    "Hyacinth flower",
    "Wisteria flower",
    "Impatien flower",
    "Hollyhock flower",
    "Lilac flower",
    "Peony flower",
    "Lupine flower",
    "Tulip flower",
    "Pansy flower",
    "Yarrow flower",
    "Salvia flower",
    "Dahlia flower",
    "Camellia flower",
    "Bougainvillea flower",
    "Foxglove flower",
    "Gladiolus flower",
    "Poppy flower",
    "Primrose flower",
    "Hydrangea flower",
    "Rhododendron flower",
    "Delphinium flower",
    "Honeysuckle flower"
]
trees=[
    "pine tree",
    "oak tree",
    "birch tree",
    "maple tree"
]
instruments=[
    "Steel Pan",
    "Wooden Flute",
    "Guitar",
    "Clarinet",
    "Trumpet",
    "Whistle",
    "Ukulele",
    "Cowbell",
    "Piccolo",
    "Acoustic Guitar",
    "French Horn",
    "Bongos",
    "Slide Whistle",
    "Bass Guitar",
    "Oboe",
    "Fiddle",
    "Steel Drums",
    "Bagpipes",
    "Violin",
    "Triangle",
    "Xylophone",
    "Kazoo",
    "Maracas",
    "Organ",
    "Shakers",
    "Zither",
    "Ocarina",
    "Harmonica",
    "Drums",
    "Saxophone",
    "Symbols",
    "Recorder",
    "Tambourine",
    "Spoons",
    "Turntables",
    "Voice",
    "Vibraphone",
    "Trombone",
    "Harp",
    "Bells",
    "Snare Drum",
    "Vocals",
    "Crystal Glasses",
    "Tuba",
    "Flute",
    "Viola",
    "Keyboard",
    "Bamboo Flute",
    "Accordion",
    "Piano",
    "Banjo"
]
# snakes=[
#     "Viper",
#     "Twig Snake",
#     "Rattlesnake",
#     "Philippine Cobra",
#     "Burrowing asp",
#     "Corn Snake",
#     "Horned Viper",
#     "Taipan",
#     "Black Mamba",
#     "Common Garter Snake",
#     "Mexican Jumping Viper",
#     "Coral cobra",
#     "Langaha Nasuta",
#     "Black Racer",
#     "Blue Krait",
#     "Spiny Tree Viper",
#     "Tiger Keelback",
#     "Eastern Brown Snake",
#     "Golden Lancehead",
#     "Ball Python",
#     "Mamushi",
#     "California King Snake",
#     "Hognosed Pitviper",
#     "Death Adder",
#     "Ringneck snake",
#     "Elephant Trunk Snake",
#     "Tiger Snake",
#     "Water Cobra",
#     "Sea Snake",
#     "Inland Taipan",
#     "Long Nosed Vine Snake",
#     "Boa Constrictor",
#     "Milk Snake",
#     "Flying Snake",
#     "Atheris Hispida",
#     "Tentacled Snake",
#     "Fierce Snake"
snakes=[
    "Viper snake",
    "Rattlesnake",
    "Cobra snake",
    "asp snake",
    "Black-Mamba snake",
    "King-Snake",
    "Pitviper snake",
    "Adder snake",
    "Boa-Constrictor snake",
    "Milk-Snake",
]
things=[
    "boom box",
    "deodorant",
    "shoes",
    "sun glasses",
    "playing card",
    "twezzers",
    "bookmark",
    "sofa",
    "computer",
    "wallet",
    "headphones",
    "stop sign",
    "teddies",
    "shirt",
    "button",
    "bread",
    "watch",
    "thermometer",
    "television",
    "perfume",
    "greeting card",
    "bag",
    "socks",
    "door",
    "toothpaste",
    "vase",
    "drill press",
    "hair brush",
    "pen",
    "knife",
    "needle",
    "tire swing",
    "tomato",
    "fork",
    "bracelet",
    "credit card",
    "tissue box",
    "desk",
    "clamp",
    "screw",
    "mp3 player",
    "sand paper",
    "air freshener",
    "candy wrapper",
    "soy sauce packet",
    "outlet",
    "conditioner",
    "balloon",
    "food",
    "scotch tape",
    "paper",
    "bananas",
    "shampoo",
    "buckle",
    "rubber band",
    "lamp shade",
    "glass",
    "lace",
    "twister",
    "helmet",
    "toe ring",
    "monitor",
    "model car",
    "milk",
    "pillow",
    "stockings",
    "leg warmers",
    "drawer",
    "flag",
    "rubber duck",
    "box",
    "toothbrush",
    "white out",
    "clothes",
    "soap",
    "eye liner",
    "mop",
    "sticky note",
    "checkbook",
    "cookie jar",
    "cinder block",
    "camera",
    "tooth picks",
    "chapter book",
    "puddle",
    "brocolli",
    "speakers",
    "bow",
    "glasses",
    "candle",
    "seat belt",
    "sidewalk",
    "plate",
    "rug",
    "pool stick",
    "glow stick",
    "chair",
    "shawl",
    "cell phone",
    "bottle",
    "hair tie",
    "photo album",
    "newspaper",
    "fake flowers",
    "paint brush",
    "sponge",
    "carrots",
    "table",
    "tv",
    "lip gloss",
    "rusty nail",
    "lamp",
    "blanket",
    "spring",
    "slipper",
    "thread",
    "lotion",
    "bowl",
    "sketch pad",
    "cup",
    "sandal",
    "packing peanuts",
    "plastic fork",
    "keyboard",
    "hanger",
    "doll",
    "keys",
    "USB drive",
    "pencil",
    "beef",
    "floor",
    "eraser",
    "clay pot",
    "purse",
    "CD",
    "cat",
    "radio",
    "nail file",
    "coasters",
    "nail clippers",
    "house",
    "grid paper",
    "water bottle",
    "bottle cap",
    "window",
    "thermostat",
    "soda can",
    "apple",
    "face wash",
    "phone",
    "cork",
    "towel",
    "chalk",
    "ring",
    "key chain",
    "shovel",
    "flowers",
    "book",
    "controller",
    "pants",
    "bed",
    "ice cube tray",
    "remote",
    "sharpie",
    "street lights",
    "canvas",
    "mouse pad",
    "toilet",
    "wagon",
    "washing machine",
    "charger",
    "shoe lace",
    "spoon",
    "picture frame",
    "money",
    "video games",
    "ipod",
    "blouse",
    "mirror",
    "zipper",
    "car",
    "couch",
    "truck",
    "chocolate",
    "sailboat",
    "magnet",
    "tree",
    "clock",
    "piano",
    "fridge"
]
insects=[
    "beetle",
    "ant",
    "ladybug",
    "bee",
    "wasp",
    "spider",
    "butterfly",
    "moth",
    "firefly",
    "dragonfly",
    "butterfly",
    "scorpion",
    "locust",
    "ant"
]
biology = [
    "hydrogen atom",
    "molecule",
    "influenze virus",
    "HIV virus",
    "ebola virus",
    "adenovirus",
    "rabies virus",
    "bacteriophage",
    "papillomavirus",
    "rotavirus",
    "hepititus C virus",
    "herpes virus"

    "DNA",
    "A-DNA",
    "B-DNA",
    "Z-DNA",

    "bacteria",
    "cocci bacteria",
    "bacilli bacteria",
    "spirochetes bacteria",

    "protozoa",
    "giardia protozoa",
    "plasmodium protozoa",
    "amoeba protozoa",
    "trypanosoma protozoa",

    "fungus",
    "teeth fungus",
    "cup fungus",
    "polypore fungus",
    "puffball fungus",
    "spores",
    "mushrooms",
    "mycelium",
]

test = [
    "cat",
    "dog",
    "rabbit",
    "elephant",
    "parrot",
    "fish",
    "tucan",
    "kangaroo",
    "tiger",
    "polar bear",
    "panther",
    "ferret",
]

ordered1 = [
    "hydrogen atom",
    "molecule",
    "DNA cell",
    "protazoa",
    "human cell",
    "spores",
    "ferns",
    "plants",
    "swamp",
    "jungle with sunlight shing through the leaves",
    "sun",
    "solar system",
    "universe"
]
dna = [
    "DNA",
    "double helix",
    "RNA",
    "genetics",
    "DNA",
    "double helix",
    "RNA",
    "genetics",
    "DNA",
    "double helix",
    "RNA",
    "genetics",
    "DNA",
    "double helix",
    "RNA",
    "genetics",
]
cells = [
    "human cell",
    "virus"
    "spores",
    "embryo",
    "germ cell",
    "cancer cell",
    "plant cell",
    "DNA cell"
    "bacteria cell",
    "protazoa",
    "hydrogen atom",
    "mycelium cell",
]
models = [
#^ center stable
    "deliberate_v2.safetensors [9aba26abdf]",
    "DUP_deliberate_v2.safetensors [9aba26abdf]",
    # "dreamlike-photoreal-2.0.ckpt [fc52756a74]",
    # "dreamshaper_5BakedVae.safetensors [a60cfaa90d]",
    # "Protogen_V2.2.ckpt [bb725eaf2e]",
    #
    # "HassanBlend1.4_Safe.safetensors [b08fdba169]",
    # "f222.ckpt [9e2c6ceff3]",
    # "meinamix_meinaV9.safetensors [eac6c08a19]",
    # "sd-v1-4.ckpt [fe4efff1e1]",
    # "v1-5-pruned-emaonly.safetensors [6ce0161689]",
    #
    # "modelshoot-1.0.safetensors [80dc271195]",
    # "openjourney-v4.ckpt [02e37aad9f]",
    # "chilloutmix_NiPrunedFp32Fix.safetensors [fc2511737a]",
    # "elldrethsRetroMix_v10.safetensors [57285e7bd5]",
    #
    # # creates girls :/
    # "ghostmix_v20Bakedvae.safetensors [e3edb8a26f]",
    # "anythingV3_fp16.ckpt [812cd9f9d9]",
    # "realisticVisionV20_v20.safetensors [c0d1994c73]",
    # "abyssorangemix3AOM3_aom3a1b.safetensors [5493a0ec49]",

]
sampler = [
    "Euler a",
    "Euler",


    "DPM2 a",
    "DPM++ 2S a",
    "DPM++ 2M",
    "DPM++ SDE",
#lots of BG noise
    "DPM fast",
    "DPM adaptive",
    "LMS Karras",
    "DPM2 Karras",
    "DPM++ 2S a Karras",
    "DPM++ 2M Karras",

    "DPM++ SDE Karras",
    "LMS",
    "DPM2",
    "Heun",
    "DPM2 a Karras",
]

#-----------------------------------------------------------------

# uniall = []
# alters1 = []
# alters2 = []
#
# # arrays= [insects,snakes,flowers,fish,birds,animals]
# arrays = [biology]
#
#
# random.shuffle(arrays)
# for a in arrays:
#     nl = random.sample(a, 10)
#     for i in nl:
#         uniall.append(i)
#
# for i in range(len(uniall)):
#     if i%2==0:
#         alters1.append(uniall[i])
#     else:
#         alters2.append(uniall[i])
#
#
# alters1 += alters1
# alters2 += alters2
#
# alters1 = shiftary(alters1)  #^ offset arrays so there are no dups in the pairs
#
